tmrvr fixed, it now actually works - the short one-line format didn't work as I expected it Additionally it shows that maya 2010, with its custom global exception handler eats up actual error codes, especially in conjunction with the intentionally broken stdin, causing the python interpreter to exit normally, although it actually dropped back into interactive mode as because it cought an exception in the first place. This can only be fixed by a custom exception handler, or at least by restoring the original one somehow. First time I tried, it didn't really work.

diff --git a/test/bin/tmrvr b/test/bin/tmrvr
--- a/test/bin/tmrvr
+++ b/test/bin/tmrvr
@@ -13,7 +13,11 @@ fi
 # the command should be rewritten in python to have a windows version as well.
 for maya_version in 8.5 2008 2009 2010 2011; do
 	# try to start the version - on failure skip it
-	echo | $base/tmrv $maya_version || echo "Skipped $maya_version as it is not installed" && continue
+	echo | $base/../../bin/mrv $maya_version
+	if [[ $? != 0 ]]; then
+		echo "Skipped $maya_version as it is not installed"
+		continue
+	fi
 	
 	for test in "" `find $base/.. -name "test_single_*.py"`; do
 		echo "tmrv $maya_version ${test##$base/../}"
@@ -22,7 +26,12 @@ for maya_version in 8.5 2008 2009 2010 2011; do
 		# in test mode - this happens for example if we run maya post 2010 which 
 		# changes the except hook. Could use a custom hook though, but this 
 		# appears to be the simplest solution
-		echo | $base/tmrv $maya_version $test || exit $?
+		echo | $base/tmrv $maya_version $test
+		if [[ $? != 0 ]]; then
+			rval=$?
+			echo "tmrv $maya_version ${test##$base/../} failed"
+			exit $rval
+		fi
 	done
 done
 
